# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GECUpAua4lhoHPyC3eQIHd9cjg3TGRZD
"""

# main.py
from data_loader import ler_dados
from model import treinar_modelo
from predict import prever
from config import DATA_PATH

if __name__ == "__main__":
    df = ler_dados(DATA_PATH)
    modelo, X_test, y_test = treinar_modelo(df)

    novo_cliente = {
        "sexo": "F",
        "posse_de_veiculo": True,
        "posse_de_imovel": False,
        "qtd_filhos": 1,
        "tipo_renda": "Empregado",
        "educacao": "Superior completo",
        "estado_civil": "Casado",
        "tipo_residencia": "Casa",
        "idade": 40,
        "tempo_emprego": 5.0,
        "qt_pessoas_residencia": 3,
        "renda": 3500.00
    }

    prob = prever(modelo, novo_cliente, X_test.columns)
    print(f"Probabilidade de inadimplência: {prob*100:.2f}%")