# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RfOPi6T1QWaq4irZajG6cM0mCfDJ5pnF
"""

# model.py
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from config import TEST_SIZE, RANDOM_STATE
from preprocess import construir_pipeline

def treinar_modelo(df, target="mau"):
    X = df.drop(columns=[target])
    y = df[target]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, stratify=y, random_state=RANDOM_STATE
    )

    preproc = construir_pipeline()
    modelo = Pipeline(steps=[
        ("preprocessamento", preproc),
        ("classificador", RandomForestClassifier(
            random_state=RANDOM_STATE,
            class_weight="balanced"
        ))
    ])

    modelo.fit(X_train, y_train)
    return modelo, X_test, y_test