# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcNB5zOwFqgS5Be24mAAY9f9q7drm8FK
"""

# predict.py
import pandas as pd

def processar_entrada(dados_entrada: dict, colunas: list) -> pd.DataFrame:
    df = pd.DataFrame([dados_entrada])
    df = df.reindex(columns=colunas, fill_value=0)
    return df

def prever(modelo, dados_dict: dict, colunas_referencia: list) -> float:
    df = processar_entrada(dados_dict, colunas_referencia)
    probas = modelo.predict_proba(df)
    return float(probas[0][1])  # Probabilidade de inadimplência