# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11luqPbUpvEwGy0j9gHcUKDUI-nTJBvKL
"""

# preprocess.py
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from config import NUM_FEATURES, CAT_FEATURES

def construir_pipeline():
    transformer = ColumnTransformer([
        ("num", StandardScaler(), NUM_FEATURES),
        ("cat", OneHotEncoder(handle_unknown='ignore'), CAT_FEATURES)
    ])

    return transformer